# Generated by Django 5.2.7 on 2025-10-31 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_category_options_remove_product_main_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='livestock_type',
            field=models.CharField(choices=[('cattle', 'cattle'), ('goats', 'Goats'), ('sheep', 'Sheep'), ('poultry', 'Poultry'), ('pigs', 'Pigs'), ('rabbits', 'Rabbits'), ('fish', 'Fish'), ('others', 'Others')], max_length=20),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('products', 'Products Report'), ('orders', 'Orders Report'), ('revenue', 'Revenue Report'), ('users', 'Users Report'), ('inventory', 'Inventory Report')], max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom Date Range')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
