# Generated by Django 5.2.7 on 2025-10-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_product_livestock_type_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='animal_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='livestock_type',
            field=models.CharField(choices=[('cattle', 'Cattle'), ('goats', 'Goats'), ('sheep', 'Sheep'), ('poultry', 'Poultry'), ('pigs', 'Pigs'), ('rabbits', 'Rabbits'), ('fish', 'Fish'), ('others', 'Others')], max_length=20),
        ),
    ]
