# Generated by Django 5.2.7 on 2025-11-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_animal_type_alter_product_livestock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Additional Image 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Additional Image 2'),
        ),
    ]
