# Generated by Django 5.2.7 on 2025-11-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_mtn_phone_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, help_text="Customer's main contact number from their profile", max_length=20, null=True, verbose_name='Customer Phone'),
        ),
    ]
